exclude: '^ppci/.*$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-executables-have-shebangs
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: double-quote-string-fixer
    -   id: mixed-line-ending
-   repo: local
    hooks:
    -   id: as
        name: Assemble examples
        language: python
        entry: tools/testas
        always_run: true
        pass_filenames: false
    -   id: cc
        name: Compile examples
        language: python
        entry: tools/testcc
        always_run: true
        pass_filenames: false
    -   id: asmunit
        name: Assembly unit tests
        language: python
        entry: ./as.py examples/asm/unittest.asm -t 226
        always_run: true
        pass_filenames: false
    -   id: cunit
        name: C unit tests
        language: python
        entry: ./cc.py examples/c/unittest.c -t 1
        always_run: true
        pass_filenames: false
