#!/usr/bin/env python3

import glob, subprocess
from typing import Sequence

def main(argv: Sequence[str] | None = None) -> int:
    filenames = glob.glob('examples/asm/*.asm')

    retval = 0
    for filename in filenames:
        code = subprocess.run(['./as.py', filename, '-o', '/dev/null']).returncode
        if code != 0:
            print(f'{filename}: failed assembly')
            retval = 1

    return retval

if __name__ == '__main__':
    raise SystemExit(main())
