#!/usr/bin/env python3

import glob, subprocess
from typing import Sequence

def main(argv: Sequence[str] | None = None) -> int:
    filenames = glob.glob('examples/c/*.c')

    retval = 0
    for filename in filenames:
        code = subprocess.run(['python', '-m', 'puc8.cc', filename, '-o', '/dev/null']).returncode
        if code != 0:
            print(f'{filename}: failed compilation')
            retval = 1

    return retval

if __name__ == '__main__':
    raise SystemExit(main())
